CrudMovies/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudMovies.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext>options) : base(options)
        {
        }

        public DbSet<Movies> Movies { get; set; }
    }
}

CrudMovies/Models/ErrorViewModel.cs
using System;

namespace CrudMovies.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudMovies/Models/Movies.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CrudMovies.Models
{
    public class Movies
    {
        [Key]
        public int idMov { get; set; }

        [Required (ErrorMessage = "Ingrese titulo de la pelicula")]
        [Display(Name = "Titulo")]
        public string nombreMov { get; set; }

        [Required (ErrorMessage = "Ingrese nombre del director")]
        [Display(Name = "Director")]
        public string directorMov { get; set; }

        [Required (ErrorMessage ="Ingrese duracion en minutos")]
        [Display(Name = "Duracion en minutos")]
        public int duracionMov { get; set; }
        

        [Required (ErrorMessage ="Ingrese año de estreno")]
        [Display(Name = "Estreno")]
        public int fechaMov { get; set; }


        [Required(ErrorMessage = "Seleccione genero")]
        [Display(Name = "Genero")]
        public string generoMov { get; set; }
    }
}

CrudMovies/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudMovies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CrudMovies.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MoviesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Movies.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string movSearch)
        {
            ViewData["GetMoviesDetails"] = movSearch;
            var empquery = from x in _db.Movies select x;
            if (!String.IsNullOrEmpty(movSearch))
            {
                empquery = empquery.Where(x => x.nombreMov.Contains(movSearch) ||
                x.generoMov.Contains(movSearch));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Movies nMov)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nMov);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nMov);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getMovDetail = await _db.Movies.FindAsync(id);
            return View(getMovDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getMovDetail = await _db.Movies.FindAsync(id);
            return View(getMovDetail);
        }


        [HttpPost]
        public async Task<ActionResult> Edit(Movies oldMov)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldMov);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldMov);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getMovDetail = await _db.Movies.FindAsync(id);
            return View(getMovDetail);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {

            var getMovDetail = await _db.Movies.FindAsync(id);
            _db.Movies.Remove(getMovDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

CrudMovies/Views/Movies/Create.cshtml
@model CrudMovies.Models.Movies

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar</h1>

<h4>Peliculas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombreMov" class="control-label"></label>
                <input asp-for="nombreMov" class="form-control" />
                <span asp-validation-for="nombreMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="directorMov" class="control-label"></label>
                <input asp-for="directorMov" class="form-control" />
                <span asp-validation-for="directorMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="duracionMov" class="control-label"></label>
                <input asp-for="duracionMov" class="form-control" />
                <span asp-validation-for="duracionMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaMov" class="control-label"></label>
                <input asp-for="fechaMov" class="form-control" />
                <span asp-validation-for="fechaMov" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="generoMov" class="control-label" style="width:600px;"></label>
                <select name="generoMov" style="width:350px;">
                    <option value="">Selecciona</option>
                    <option value="Accion">Accion</option>
                    <option value="Aventura">Aventura</option>
                    <option value="Comedia">Comedia</option>
                    <option value="Infantil">Infantil</option>
                    <option value="Terror">Terror</option>
                    <option value="Romance">Romance</option>
                </select>

            </div>


            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudMovies/Views/Movies/Delete.cshtml
@model CrudMovies.Models.Movies

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Seguro que quiere eliminar el registro?</h3>
<div>
    <h4>Peliculas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombreMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombreMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.directorMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.directorMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.duracionMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.duracionMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechaMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechaMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.generoMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.generoMov)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

CrudMovies/Views/Movies/Detail.cshtml
@model CrudMovies.Models.Movies

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles</h1>

<div>
    <h4>Peliculas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.idMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.idMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombreMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombreMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.directorMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.directorMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.duracionMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.duracionMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechaMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechaMov)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.generoMov)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.generoMov)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Regresar</a>
</div>

CrudMovies/Views/Movies/Edit.cshtml
@model CrudMovies.Models.Movies

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Peliculas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="idMov" class="control-label"></label>
                <input asp-for="idMov" class="form-control" readonly />
                <span asp-validation-for="idMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nombreMov" class="control-label"></label>
                <input asp-for="nombreMov" class="form-control" />
                <span asp-validation-for="nombreMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="directorMov" class="control-label"></label>
                <input asp-for="directorMov" class="form-control" />
                <span asp-validation-for="directorMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="duracionMov" class="control-label"></label>
                <input asp-for="duracionMov" class="form-control" />
                <span asp-validation-for="duracionMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaMov" class="control-label"></label>
                <input asp-for="fechaMov" class="form-control" />
                <span asp-validation-for="fechaMov" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="generoMov" class="control-label" style="width:500px;"></label>
                <select name="generoMov" style="width:350px;">
                    <option value="">Selecciona</option>
                    <option value="Accion">Accion</option>
                    <option value="Aventura">Aventura</option>
                    <option value="Terror">Terror</option>
                    <option value="Comedia">Comedia</option>
                    <option value="Romance">Romance</option>
                </select>

            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudMovies/Views/Movies/Index.cshtml
@model IEnumerable<CrudMovies.Models.Movies>

@{
    ViewData["Title"] = "Index";
}
    <body background="img/cine.jpg">
        <h1>Peliculas</h1>

        <p>
            <a asp-action="Create">Agregar</a>
        </p>

        <form asp-action="Index" method="get">
            <input type="search" placeholder="Busca por titulo o por genero" name="movSearch"
                   value="@ViewData["GetMoviesDetails"]" style="width:300px;" />
            <input type="submit" value="Buscar" class="btn btn-outline-dark" />
            <a asp-action="Index" class="btn btn-outline-dark">Ver todos</a>
        </form>


        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.nombreMov)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.directorMov)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.duracionMov)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fechaMov)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.generoMov)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombreMov)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.directorMov)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.duracionMov)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.fechaMov)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.generoMov)
                        </td>
                        <td>
                            @Html.ActionLink("Detalles", "Detail", new { id = item.idMov }, new { @class = "btn btn-outline-warning" })
                            @Html.ActionLink("Modificar", "Edit", new { id = item.idMov }, new { @class = "btn btn-outline-success" })
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.idMov }, new { @class = "btn btn-outline-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </body>

CrudMovies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudMovies</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">CrudMovies</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CrudMovies
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>