CrudClientes/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrudClientes.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext>options): base(options)
        {
        }
        public DbSet<Cliente> Cliente
        {
            get;
            set;
        }
    }
}

CrudClientes/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace CrudClientes.Models
{
    public class Cliente
    {
        [Key]
        public int IdCliente { get; set; }

        [Required(ErrorMessage = "Ingresa nombre del cliente")]
        [Display(Name = "Nombre")]
        public string NombreCliente { get; set; }

        [Required(ErrorMessage = "Ingresa credito del cliente")]
        [Display(Name = "Credito")]
        public int CreditoCliente { get; set; }

        [Required(ErrorMessage = "Ingresa edad del cliente")]
        [Display(Name = "Edad")]
        [Range(20, 50)]
        public int EdadCliente { get; set; }

        [Required(ErrorMessage = "Ingresa tu correo")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Ingresa un correo valido")]
        public string CorreoCliente { get; set; }



    }
}

CrudClientes/Models/ErrorViewModel.cs
using System;

namespace CrudClientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudClientes/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CrudClientes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CrudClientes.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Cliente.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string cliSearch)
        {
            ViewData["GetCliDetails"] = cliSearch;
            var empquery = from x in _db.Cliente select x;
            if (!String.IsNullOrEmpty(cliSearch))
            {
                empquery = empquery.Where(x => x.NombreCliente.Contains(cliSearch) ||
                x.CorreoCliente.Contains(cliSearch));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Cliente nCli)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nCli);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nCli);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCliDetail = await _db.Cliente.FindAsync(id);
            return View(getCliDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCliDetail = await _db.Cliente.FindAsync(id);
            return View(getCliDetail);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Cliente oldCli)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldCli);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldCli);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCliDetail = await _db.Cliente.FindAsync(id);
            return View(getCliDetail);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {

            var getCliDetail = await _db.Cliente.FindAsync(id);
            _db.Cliente.Remove(getCliDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }




    }
}

CrudClientes/Views/Cliente/Create.cshtml
@model CrudClientes.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Agrega un nuevo cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoCliente" class="control-label"></label>
                <input asp-for="CreditoCliente" class="form-control" />
                <span asp-validation-for="CreditoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadCliente" class="control-label"></label>
                <input asp-for="EdadCliente" class="form-control" />
                <span asp-validation-for="EdadCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoCliente" class="control-label"></label>
                <input asp-for="CorreoCliente" class="form-control" />
                <span asp-validation-for="CorreoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudClientes/Views/Cliente/Delete.cshtml
@model CrudClientes.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>¿Estas seguro de querer eliminar a este cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreditoCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EdadCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EdadCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CorreoCliente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CrudClientes/Views/Cliente/Detail.cshtml
@model CrudClientes.Models.Cliente

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreditoCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EdadCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EdadCliente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoCliente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CorreoCliente)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

CrudClientes/Views/Cliente/Edit.cshtml
@model CrudClientes.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" readonly />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoCliente" class="control-label"></label>
                <input asp-for="CreditoCliente" class="form-control" />
                <span asp-validation-for="CreditoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadCliente" class="control-label"></label>
                <input asp-for="EdadCliente" class="form-control" />
                <span asp-validation-for="EdadCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoCliente" class="control-label"></label>
                <input asp-for="CorreoCliente" class="form-control" />
                <span asp-validation-for="CorreoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudClientes/Views/Cliente/Index.cshtml
@model IEnumerable<CrudClientes.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Create">Agregar</a>
</p>

<form asp-action="Index" method="get">
    <input type="search" placeholder="Nombre o email..." name="cliSearch"
           value="@ViewData["GetClienteDetails"]" style="width:500px;" />
    <input type="submit" value="buscar" class="btn btn-primary" />
    <a asp-action="Index">Ver todos</a>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditoCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EdadCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoCliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreditoCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EdadCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorreoCliente)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdCliente }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.IdCliente }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Borrar", "Delete", new { id = item.IdCliente }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        }
    </tbody>
</table>

CrudClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudClientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index">CrudClientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CrudClientes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>